import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import AppShell from '@/components/AppShell';
import { useApp, formatPKR } from '@/context/AppContext';
import { ArrowLeft, FileDown, Check, Trash2, Mail, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/context/AuthContext';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { supabase } from '@/integrations/supabase/client';

export default function InvoiceView() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { brand, clients, invoices, setInvoices } = useApp();
  const { toast } = useToast();
  const { user } = useAuth();
  const [sending, setSending] = useState(false);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailTo, setEmailTo] = useState('');

  const inv = invoices.find(i => i.id === id);
  if (!inv) {
    return (
      <AppShell>
        <div className="text-center py-20">
          <p className="font-body text-muted-foreground mb-4">Invoice not found</p>
          <button onClick={() => navigate('/invoices')} className="bg-foreground text-primary-foreground px-6 py-2.5 rounded-full font-body text-sm font-medium">
            Back to Invoices
          </button>
        </div>
      </AppShell>
    );
  }

  const client = clients.find(c => c.id === inv.clientId);
  const subtotal = inv.items.reduce((s, i) => s + i.qty * i.unitPrice, 0);
  const taxRate = brand.taxRate || 0;
  const taxAmount = subtotal * (taxRate / 100);
  const total = inv.amount;

  const markPaid = () => {
    setInvoices(prev => prev.map(i => i.id === inv.id ? { ...i, status: 'paid' as const } : i));
    toast({ title: 'Marked as paid ✓' });
  };

  const deleteInvoice = () => {
    setInvoices(prev => prev.filter(i => i.id !== inv.id));
    toast({ title: 'Invoice deleted ✓' });
    navigate('/invoices');
  };

  const generatePDFBase64 = (): string => {
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text(brand.businessName || 'BillBook', 14, 25);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`${brand.city || ''} | ${brand.phone || ''}`, 14, 32);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.text('INVOICE', 140, 25);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(inv.number, 140, 32);
    doc.text(`Date: ${inv.date}`, 140, 38);
    doc.text(`Due: ${inv.dueDate || 'N/A'}`, 140, 44);
    doc.setDrawColor(200);
    doc.line(14, 50, 196, 50);
    doc.setFontSize(10);
    doc.text('Bill To:', 14, 58);
    doc.setFont('helvetica', 'bold');
    doc.text(inv.clientName, 14, 64);
    doc.setFont('helvetica', 'normal');
    autoTable(doc, {
      startY: 75,
      head: [['Description', 'Qty', 'Unit Price', 'Total']],
      body: inv.items.map(i => [i.description, String(i.qty), formatPKR(i.unitPrice), formatPKR(i.qty * i.unitPrice)]),
      theme: 'plain',
      headStyles: { fillColor: [28, 25, 23], textColor: [255, 255, 255], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      alternateRowStyles: { fillColor: [250, 248, 245] },
    });
    const finalY = (doc as any).lastAutoTable?.finalY || 110;
    doc.setFontSize(10);
    doc.text(`Subtotal: ${formatPKR(subtotal)}`, 140, finalY + 10);
    doc.text(`Tax (${taxRate}%): ${formatPKR(taxAmount)}`, 140, finalY + 17);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(`Total: ${formatPKR(total)}`, 140, finalY + 27);
    if (inv.notes) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text('Payment Details:', 14, finalY + 40);
      doc.text(inv.notes, 14, finalY + 46);
    }
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by BillBook • billbook.pk', 14, 285);
    return doc.output('datauristring').split(',')[1]; // base64 only
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text(brand.businessName || 'BillBook', 14, 25);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`${brand.city || ''} | ${brand.phone || ''}`, 14, 32);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.text('INVOICE', 140, 25);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(inv.number, 140, 32);
    doc.text(`Date: ${inv.date}`, 140, 38);
    doc.text(`Due: ${inv.dueDate || 'N/A'}`, 140, 44);
    doc.setDrawColor(200);
    doc.line(14, 50, 196, 50);
    doc.setFontSize(10);
    doc.text('Bill To:', 14, 58);
    doc.setFont('helvetica', 'bold');
    doc.text(inv.clientName, 14, 64);
    doc.setFont('helvetica', 'normal');
    autoTable(doc, {
      startY: 75,
      head: [['Description', 'Qty', 'Unit Price', 'Total']],
      body: inv.items.map(i => [i.description, String(i.qty), formatPKR(i.unitPrice), formatPKR(i.qty * i.unitPrice)]),
      theme: 'plain',
      headStyles: { fillColor: [28, 25, 23], textColor: [255, 255, 255], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      alternateRowStyles: { fillColor: [250, 248, 245] },
    });
    const finalY = (doc as any).lastAutoTable?.finalY || 110;
    doc.setFontSize(10);
    doc.text(`Subtotal: ${formatPKR(subtotal)}`, 140, finalY + 10);
    doc.text(`Tax (${taxRate}%): ${formatPKR(taxAmount)}`, 140, finalY + 17);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(`Total: ${formatPKR(total)}`, 140, finalY + 27);
    if (inv.notes) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text('Payment Details:', 14, finalY + 40);
      doc.text(inv.notes, 14, finalY + 46);
    }
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by BillBook • billbook.pk', 14, 285);
    doc.save(`${inv.number}-${inv.clientName}.pdf`);
    toast({ title: 'PDF downloaded ✓' });
  };

  const openEmailModal = () => {
    setEmailTo(client?.email || '');
    setShowEmailModal(true);
  };

  const sendEmail = async () => {
    if (!emailTo) {
      toast({ title: 'Please enter an email address', variant: 'destructive' });
      return;
    }
    setSending(true);
    try {
      const pdfBase64 = generatePDFBase64();
      const subject = `${brand.invoicePrefix || 'Invoice'} ${inv.number} from ${brand.businessName || 'BillBook'}`;

      const { data, error } = await supabase.functions.invoke('send-invoice-email', {
        body: {
          to: emailTo,
          subject,
          businessName: brand.businessName,
          businessCity: brand.city,
          businessPhone: brand.phone,
          brandColor: brand.brandColor,
          invoiceNumber: inv.number,
          invoiceDate: inv.date,
          dueDate: inv.dueDate,
          clientName: inv.clientName,
          items: inv.items,
          subtotal,
          taxRate,
          taxAmount,
          total,
          notes: inv.notes,
          pdfBase64,
          fromEmail: `${brand.businessName || 'BillBook'} <${user?.email || 'onboarding@resend.dev'}>`,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      toast({ title: 'Invoice emailed ✓' });
      setShowEmailModal(false);
    } catch (err: any) {
      console.error('Email error:', err);
      toast({ title: 'Failed to send email', description: err.message, variant: 'destructive' });
    } finally {
      setSending(false);
    }
  };

  const statusBadge = (status: string) => {
    const styles: Record<string, string> = {
      paid: 'bg-sage-light text-sage',
      unpaid: 'bg-blush/30 text-foreground',
      overdue: 'bg-destructive/10 text-destructive',
      draft: 'bg-muted text-muted-foreground',
    };
    return `px-3 py-1 rounded-full text-xs font-body font-medium capitalize ${styles[status] || styles.draft}`;
  };

  return (
    <AppShell>
      <div className="animate-fade-up pb-20 md:pb-0">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
          <div className="flex items-center gap-3">
            <button onClick={() => navigate('/invoices')} className="p-2 rounded-xl hover:bg-muted transition-colors">
              <ArrowLeft size={18} strokeWidth={1.5} />
            </button>
            <div>
              <h1 className="font-heading text-2xl font-bold">{inv.number}</h1>
              <span className={statusBadge(inv.status)}>{inv.status}</span>
            </div>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <button onClick={downloadPDF} className="flex items-center gap-2 border border-border px-5 py-2.5 rounded-full font-body text-sm font-medium hover:bg-muted transition-colors">
              <FileDown size={15} strokeWidth={1.5} /> Download PDF
            </button>
            <button onClick={openEmailModal} className="flex items-center gap-2 bg-foreground text-primary-foreground px-5 py-2.5 rounded-full font-body text-sm font-medium hover:opacity-90 transition-opacity">
              <Mail size={15} strokeWidth={1.5} /> Email Invoice
            </button>
            {inv.status !== 'paid' && (
              <button onClick={markPaid} className="flex items-center gap-2 bg-sage text-primary-foreground px-5 py-2.5 rounded-full font-body text-sm font-medium hover:opacity-90 transition-opacity">
                <Check size={15} strokeWidth={1.5} /> Mark Paid
              </button>
            )}
            <button onClick={deleteInvoice} className="flex items-center gap-2 border border-destructive/30 text-destructive px-5 py-2.5 rounded-full font-body text-sm font-medium hover:bg-destructive/10 transition-colors">
              <Trash2 size={15} strokeWidth={1.5} /> Delete
            </button>
          </div>
        </div>

        {/* Invoice Preview */}
        <div className="max-w-2xl mx-auto bg-card border border-border rounded-2xl p-8 shadow-sm">
          <div className="flex justify-between items-start mb-6">
            <div>
              {brand.logo && <img src={brand.logo} alt="Logo" className="h-8 mb-2" />}
              <div className="font-heading text-lg font-bold">{brand.businessName || 'Your Business'}</div>
              <div className="font-body text-xs text-muted-foreground">{brand.city} • {brand.phone}</div>
            </div>
            <div className="text-right">
              <div className="font-heading text-2xl font-bold">INVOICE</div>
              <div className="font-mono text-xs text-muted-foreground mt-1">{inv.number}</div>
              <div className="font-body text-xs text-muted-foreground">Date: {inv.date}</div>
              {inv.dueDate && <div className="font-body text-xs text-muted-foreground">Due: {inv.dueDate}</div>}
            </div>
          </div>

          <div className="h-0.5 w-full mb-4" style={{ backgroundColor: brand.brandColor || '#1C1917' }} />

          <div className="mb-6">
            <div className="font-body text-xs text-muted-foreground">Bill To</div>
            <div className="font-body text-sm font-medium">{inv.clientName}</div>
          </div>

          <table className="w-full mb-4 text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="text-left py-2 font-body text-xs text-muted-foreground">Description</th>
                <th className="text-center py-2 font-body text-xs text-muted-foreground">Qty</th>
                <th className="text-right py-2 font-body text-xs text-muted-foreground">Price</th>
                <th className="text-right py-2 font-body text-xs text-muted-foreground">Total</th>
              </tr>
            </thead>
            <tbody>
              {inv.items.map((item, idx) => (
                <tr key={idx} className={idx % 2 === 1 ? 'bg-background' : ''}>
                  <td className="py-2 font-body text-xs">{item.description || '—'}</td>
                  <td className="py-2 font-mono text-xs text-center">{item.qty}</td>
                  <td className="py-2 font-mono text-xs text-right">{formatPKR(item.unitPrice)}</td>
                  <td className="py-2 font-mono text-xs text-right">{formatPKR(item.qty * item.unitPrice)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="border-t border-border pt-3 space-y-1 text-right">
            <div className="flex justify-end gap-6 font-body text-xs">
              <span className="text-muted-foreground">Subtotal</span>
              <span className="font-mono">{formatPKR(subtotal)}</span>
            </div>
            <div className="flex justify-end gap-6 font-body text-xs">
              <span className="text-muted-foreground">Tax ({taxRate}%)</span>
              <span className="font-mono">{formatPKR(taxAmount)}</span>
            </div>
            <div className="flex justify-end gap-6 pt-2 border-t border-border">
              <span className="font-body font-medium">Total</span>
              <span className="font-mono text-lg font-bold">{formatPKR(total)}</span>
            </div>
          </div>

          {inv.notes && (
            <div className="mt-6 pt-4 border-t border-border">
              <div className="font-body text-xs text-muted-foreground whitespace-pre-line">{inv.notes}</div>
            </div>
          )}

          <div className="mt-8 text-center">
            <div className="font-body text-xs text-muted-foreground/50">Generated by BillBook • billbook.pk</div>
          </div>
        </div>
      </div>

      {/* Email Modal */}
      {showEmailModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 backdrop-blur-sm" onClick={() => !sending && setShowEmailModal(false)}>
          <div className="bg-card rounded-2xl border border-border p-6 w-full max-w-md mx-4 animate-fade-up" onClick={e => e.stopPropagation()}>
            <h2 className="font-heading text-xl font-bold mb-1">Email Invoice</h2>
            <p className="font-body text-xs text-muted-foreground mb-5">
              A branded email with PDF attachment will be sent
            </p>

            <div className="space-y-4">
              <div>
                <label className="font-body text-xs text-muted-foreground mb-1 block">Recipient Email</label>
                <input value={emailTo} onChange={e => setEmailTo(e.target.value)} placeholder="client@email.com" type="email"
                  className="w-full bg-transparent border-b border-border py-2 font-body text-sm outline-none focus:border-sage placeholder:text-muted-foreground/50" />
              </div>
              <div>
                <label className="font-body text-xs text-muted-foreground mb-1 block">Subject</label>
                <div className="font-body text-sm py-2 text-muted-foreground">
                  {brand.invoicePrefix || 'Invoice'} {inv.number} from {brand.businessName || 'BillBook'}
                </div>
              </div>
              <div>
                <label className="font-body text-xs text-muted-foreground mb-1 block">Attachment</label>
                <div className="font-body text-sm py-2 flex items-center gap-2">
                  <FileDown size={14} strokeWidth={1.5} className="text-sage" />
                  {inv.number}-{inv.clientName}.pdf
                </div>
              </div>
            </div>

            <button onClick={sendEmail} disabled={sending}
              className="w-full mt-6 bg-foreground text-primary-foreground py-3 rounded-full font-body text-sm font-medium hover:opacity-90 transition-opacity disabled:opacity-50 flex items-center justify-center gap-2">
              {sending ? <><Loader2 size={15} className="animate-spin" /> Sending...</> : <><Mail size={15} strokeWidth={1.5} /> Send Email</>}
            </button>
          </div>
        </div>
      )}
    </AppShell>
  );
}
